INSERT INTO departments (name)
VALUES
    ('Accounting'),
    ('Sales'),
    ('Operations'),
    ('Human Resources'),
    ('Finance'),
    ('Engineering'),
    ('Marketing');

INSERT INTO roles (title, salary, department_id)
VALUES
    ('Accountant', 100000, 1),
    ('Bookeeper', 50000, 1),
    ('Accounting Manager', 50000, 1),
    ('Sales Representative', 70000, 2),
    ('Account Manager', 120000, 2),
    ('Sales Manager', 160000, 2),
    ('Ops Manager', 100000, 3),
    ('Facilitator', 65000, 3),
    ('HR Manager', 80000, 4),
    ('HR Assistant', 40000, 4),
    ('Finance Clerk', 45000, 5),
    ('Risk Analyst', 85000, 5),
    ('Finance Director', 140000, 5),
    ('Software Engineer', 90000, 6),
    ('Firmware Engineer', 100000, 6),
    ('Tech Lead', 160000, 6),
    ('Marketing Coordinator', 45000, 7),
    ('Marketing Manager', 80000, 7),
    ('Marketing Director', 110000, 7);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES
    ('Ambra','Kopp', 3, NULL),
    ('Isaac','Brigham', 6, NULL),
    ('Mairin','Hurst', 7, NULL),
    ('Hauke','Kynaston', 9, NULL),
    ('Bettina','Denis', 13, NULL),
    ('Lavrentios','Hailey', 16, NULL),
    ('Zvezdana',"O'Donnell", 19, NULL),
    ('Rochus','Rothenberg', 18, NULL),
    ('Dana','Beaumont', 1, 1),
    ('Garth','Martinović', 1, 1),
    ('Alina','Huber', 1, 1),
    ('Louise','Armati', 2, 1),
    ('Vilma','Kruger', 2, 1),
    ('Randolph', 'Blakesley', 4, 2),
    ('Vladana', 'Hirsch', 4, 2),
    ('Alexandrina', 'Ward', 4, 2),
    ('Jonathan','Miyata', 4, 2),
    ('Denys','Tani', 4, 2),
    ('Shelton', 'Gerhardt', 4, 2),
    ('Rowen', 'Norris', 4, 2),
    ('Jeannine', 'Foghladha', 4, 2),
    ('Pinelopi', 'Gautier', 5, 2),
    ('Joy', 'Abbott', 5, 2),
    ('Finlay', 'Morriss', 5, 2),
    ('Lucas', 'Nicolai', 5, 2),
    ('Mahala', 'Barbieri', 5, 2),
    ('Avery', 'Maguire', 5, 2),
    ('Erminia', 'Leblanc', 5, 2),
    ('Antonia', 'Eustis', 5, 2),
    ('Githa', 'Wheatley', 5, 2),
    ('Harve', 'Lynn', 8, 3),
    ('Roni', 'Bonaccorso', 8, 3),
    ('Floriano', 'Mihailovic', 8, 3),
    ('Christmas', 'Knezevic', 10, 4),
    ('Sunny', 'Dubhain', 10, 4),
    ('Walburga', 'Deasmhumhain', 10, 4),
    ('Hachiro', 'Valerio', 11, 5),
    ('Braiden', 'Mac Aodhagain', 11, 5),
    ('Berta', 'Lamb', 12, 5),
    ('Johnie', 'Dufort', 12, 5),
    ('Crescentia', 'Scully', 14, 6),
    ('Elias', 'Grillo', 14, 6),
    ('Joy', 'Sasaki', 14, 6),
    ('Sharla', 'Giuliani', 14, 6),
    ('Neely', 'Hashemi', 14, 6),
    ('Doretta', 'Clifford', 14, 6),
    ('Kashton', 'Hayter', 14, 6),
    ('Melissa', 'Ruskin', 14, 6),
    ('Lottie', 'Adimari', 15, 6),
    ('Micheal', 'Hoffman', 15, 6),
    ('Felicia', 'Ko', 15, 6),
    ('Irene', 'Mac Cnaimhin', 15, 6),
    ('Zorana', 'Leccese', 15, 6),
    ('Pamella', 'Bagley', 15, 6),
    ('Alberte', 'Garrett', 17, 8),
    ('Kunigunde', 'Kruger', 17, 8),
    ('Sanford', 'Cary', 17, 8),
    ('Humphry', 'Mari', 17, 8),
    ('Cyrille', 'Akerman', 17, 8),
    ('Lettice', 'Garrett', 17, 8);

    

